apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-srdn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-srdn
    app.kubernetes.io/part-of: ci10t-786-0057-app
  name: devfile-sample-srdn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-srdn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-srdn
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0057-tenant/ci10t-786-0057-app/devfile-sample-srdn@sha256:5f7bccc0fed7733b1a6a8c8108a5756d2b900d77e56e60131d8fa4412a62f355
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
