apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-srdn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0057-tenant/ci10t-786-0057-app/devfile-sample-srdn@sha256:5f7bccc0fed7733b1a6a8c8108a5756d2b900d77e56e60131d8fa4412a62f355
        name: my-nodejs
        resources: {}
status: {}
